export { default as NavbarSec } from './NavbarSec/NavbarSec'
export { default as VidSec } from './VidSec/VidSec'
export { default as TopicsMobSec } from './TopicsMobSec/TopicsMobSec'
export { default as MaterialsSec } from './MaterialsSec/MaterialsSec'
export { default as CommentsSec } from './CommentsSec/CommentsSec'